name: GrowthBook Code References (standalone)
description: Use the `gb-find-code-refs` utility to find references to feature flags in your code.
author: GrowthBook
branding:
  icon: toggle-right
  color: purple
inputs: 
  flagsPath:
    description: "Path to JSON file containing an array of feature key strings."
    required: true
  dir:
    description: "Path to directory containing codebase to be scanned."
    required: true
  branch:
    description: "Name of the branch"
    required: true
  allowTags: 
    default: "false"
    description: "Enable storing references for tags. Lists the tag as a branch."
    required: false
  contextLines: 
    default: "2"
    description: "The number of context lines to include with each code reference. If 0, only the lines containing flag references will be sent. If > 0, will include that number of context lines above and below the flag reference. A maximum of 5 context lines may be provided. (default 2)"
    required: false
  debug: 
    default: "false"
    description: "Enable verbose debug logging."
    required: false
  lookback: 
    default: "10"
    description: "Set the number of commits to search in history for whether you removed a feature flag from code. You may set to 0 to disable this feature. Setting this option to a high value will increase search time."
    required: false
  outFile:
    default: "coderefs.json"
    description: "Set the filename of the output JSON containing all code references. Defaults to 'coderefs.json'"
    required: false
  repoName:
    description: "Define the repo name so that it is included in the output JSON."
    required: false
  deleteMissing:
    default: "false"
    description: "Delete references to feature flags that are no longer found in the codebase."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GB_FLAGS_PATH: ${{ inputs.flagsPath }}
    GB_DIR: ${{ inputs.dir }}
    GB_BRANCH: ${{ inputs.branch }}
    GB_OUT_FILE: ${{ inputs.outFile }}
    GB_CONTEXT_LINES: ${{ inputs.contextLines }}
    GB_ALLOW_TAGS: ${{ inputs.allowTags }}
    GB_DEBUG: ${{ inputs.debug }}
    GB_LOOKBACK: ${{ inputs.lookback }}
    GB_REPO_NAME: ${{ inputs.repoName }}
    GB_DELETE_MISSING: ${{ inputs.deleteMissing }}
